### ISSUE TITLE
Hmac creation in Safari 10 result in extended string

### ISSUE THREAD

**Issue by herpiko** [crypto-browserify/createHmac#12]
These are results from other browser (Chrome) :

- `awDp8ybFP1tFzgplIV58sbALByOzlx8OPV9s+lld6xA=`
- `qDF6LWewvnZcaQd0+A/FxDGxVG0xGUBQuatABsmzT7M=`
- `qDF6LWewvnZcaQd0+A/FxDGxVG0xGUBQuatABsmzT7M=`

And these are from Safari 10 :

- `VWZ/cj/Q5zB0bUmwuUN9OD2TwcdbOmMhYpkw7c/6EDo=EDoAAAAA`
- `EdRN9JZabLUe14OfKcDznZCrC2jVi73D0YqNnbVpnzE=nzEAAAAA` 
- `RwRVP0eWsakNpP7knPm3/u0PveGgFZCAKpXpkPPfswU=swUAAAAA`

It seems that create-hmac generates more string like `EDoAAAAA`, `nzEAAAAA`, `swUAAAAA`. This break my Hawk auth in Safari 10.0.

**Comment by dcousens** [comment]
Why did you close @herpiko ?

**Comment by herpiko** [comment]
@dcousens I can't reproduce it in isolated env. It only happens on my current project. 

I'll open it again if I found a way to reproduce.

**Comment by zopthemop** [comment]
This happens to us as well, but in Edge (version 38.14393.0.0) via the jwt-simple library (thus breaking encoding and decoding for Edge).

Tokens generated in Edge:
```
jwt.encode({query: "foo"}, 'jwtform', 'HS256')
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxdWVyeSI6ImZvbyJ9.tUOJCqukb5sibTdAH6WNjUSD4opowurJbeVJp6aZpe8pe8AAAAA"
jwt.encode({query: "fooz"}, 'jwtform', 'HS256')
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxdWVyeSI6ImZvb3oifQ.rzoaVpnWK7LjxE5SPp1O_3Ov1FxD6J_1YfdC3ieD3KU3KUAAAAA"
```


Tokens generated in Chrome:
```
jwt.encode({query: "foo"}, 'jwtform', 'HS256')
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxdWVyeSI6ImZvbyJ9.tUOJCqukb5sibTdAH6WNjUSD4opowurJbeVJp6aZpe8"
jwt.encode({query: "fooz"}, 'jwtform', 'HS256')
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxdWVyeSI6ImZvb3oifQ.rzoaVpnWK7LjxE5SPp1O_3Ov1FxD6J_1YfdC3ieD3KU"
```

From the previous discussion, I gather this is due to some broken combination of packages?

**Comment by zopthemop** [comment]
Upon further investigation, this seems to occur because our project uses JSPM to build the package, which in our case inserts npm:buffer@3.6.0 to fulfill the Buffer dependency. The issue does not occur if we manually set it to use the latest version; npm:buffer@5.0.6.

**Comment by calvinmetcalf** [comment]
So you probably need to upgrade the version of jspm

**Comment by herpiko** [comment]
Hi, 

Now I remember how to reproduce the issue within the hawk library. There are `browser.js` and `client.js` in [hawk lib](https://github.com/hueniverse/hawk/tree/master/lib). I was though that hawk's client should use `client.js`, even in browser.  It generates the `AAAA` string. Then I'm switch to `browser.js` and the `AAAAA` was gone.

I'm sorry for not updating this issue immediatelly after I found the culprit.
