### ISSUE TITLE
[1.1.6] Buffer.alloc is not a function

### ISSUE THREAD

**Issue by collenbrecht** [crypto-browserify/createHmac#20]
TypeError: Buffer.alloc is not a function
in create-hmac@1.1.6/legacy.js

**Comment by calvinmetcalf** [comment]
this may be a bundling error, buffer refers to `var Buffer = require('safe-buffer').Buffer` and safe-buffer should have alloc on it

**Comment by briansneddon** [comment]
I think one of the issues is that safe-buffer requires the buffer package however since buffer is not specified in the safe-buffer package.json there's no constraint on the version that will satisfy it. Some of the older buffer packages releases do not support alloc.

**Comment by mikew** [comment]
I'm not sure where it's coming from for me yet, but it's happening with browserify for me.

**Comment by dcousens** [comment]
Does anyone have easy repro steps?

**Comment by daaain** [comment]
If you paste the code sample from the README to RequireBin you'll get the Buffer error on the console, see: http://requirebin.com/?gist=ea94116908e96710a648ad3f47407636

**Comment by calvinmetcalf** [comment]
jspm/registry#1049 seems to be the fix

**Comment by calvinmetcalf** [comment]
@briansneddon opened an issue based on your thing on safe-buffer feross/safe-buffer#9

**Comment by s890081tonyhsu** [comment]
I have the same issue at my repo, so I reference from here to wait for your next updates.

**Comment by nikashitsa** [comment]
I have same issue with browserify for me.

**Comment by ilovett** [comment]
workaround is to use shrinkwrap

```
cd node_modules/browserify/node_modules/crypto-browserify
npm install pbkdf2@3.0.9
npm install create-hmac@1.1.4
cd ../../../../
npm shrinkwrap --dev
```

hopefully you dont run into any shrinkwrap errors... if so try `npm prune`

**Comment by jreading** [comment]
Are there fixes in those packages that should be PR'd?

**Comment by calvinmetcalf** [comment]
there is a pull on safe-buffer feross/safe-buffer#10

**Comment by minwan** [comment]
ETA for the fix? thanks!

**Comment by dcousens** [comment]
Closing in favour of https://github.com/feross/safe-buffer/pull/10
