### ISSUE TITLE
.digest() doesn't correctly take in formatting

### ISSUE THREAD

**Issue by tmcw** [crypto-browserify/createHmac#3]
The `.digest(encoding)` method from [node](http://nodejs.org/api/crypto.html#crypto_hmac_digest_encoding) should take a string representing an encoding of `'hex', 'binary' or 'base64'`. The `digest(encoding)` method in create-hmac takes [enc and instead treats it as a boolean](https://github.com/crypto-browserify/createHmac/blob/master/browser.js#L65), leading to output either as a buffer or as a stringified buffer that ends up being a non-ascii string.

This is a regression when the fn was split out - before it worked, because `.toString()` got the right argument: https://github.com/crypto-browserify/crypto-browserify/commit/ca6d693c6462e8e698531ccc4c2e948b8f802a11#diff-4168fbe864ac9d6edb7f0efa2b9baf22L54

**Comment by dcousens** [comment]
This should be fixed by https://github.com/crypto-browserify/createHmac/commit/57725d0d7261b91c2fd650591310fb60a86ffec7
