### ISSUE TITLE
Add tests for encoding parameters

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/createHmac#5]

**Comment by dcousens** [comment]
Having trouble with `utf8`, @calvinmetcalf could you look into it?

**Comment by calvinmetcalf** [comment]
the native node crypto fails this test as well, utf isn't an encoding that crypto supports, we're excibiting the same results as node, going to revert the failing test

**Comment by calvinmetcalf** [comment]
well not revert, just remove utf8

**Comment by calvinmetcalf** [comment]
wait no binary is the other encoding adding that in (it works btw)

**Comment by dcousens** [comment]
@calvinmetcalf is this done?

**Comment by dcousens** [comment]
This has been done.   See https://github.com/crypto-browserify/createHmac/blob/master/test.js#L13
