### ISSUE TITLE
1.1.2 is broken

### ISSUE THREAD

**Issue by gribbet** [crypto-browserify/createHmac#6]
Looks like the issue is already fixed in 10a14afe297dcfc01483e57430ae2a6b3816d0d7
This is breaking a whole bunch of packages in the npm ecosystem. Please release 1.1.3

**Comment by calvinmetcalf** [comment]
done thought it was already published, have this cute ascii cat as my apology 

    ლ(●ↀωↀ●)ლ

**Comment by dcousens** [comment]
I unpublished 1.1.2 as crypto is serious business.  Deprecate wouldn't have been severe enough.

**Comment by dcousens** [comment]
I unpublished `1.1.2` as crypto is serious business.  Deprecate wouldn't have been severe enough. @dominictarr thoughts?

**Comment by dominictarr** [comment]
@dcousens yeah, I think this is a good practice, especially considering that crypto-browserify is a bit weird, being a polyfill, other modules do not depend on it directly.
